config/routes.rb
Rails.application.routes.draw do
  # devise関連のルーティング
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  # 検索機能のルーティング
  get 'search' => 'searches#search', as: 'search'

  # 謎解き投稿関連のルーティング
  get 'sort' => 'mysteries#sort', as: 'sort'
  resources :mysteries do
    # コメント機能
    resources :comments, only: %i[create update destroy]
    # いいね機能
    resource :favorites, only: %i[create destroy]
  end

  # 退会機能のルーティング
  # 退会確認画面の表示
  get 'users/unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  # ユーザーの有効ステータスを更新
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'users/withdraw' => 'users#withdraw'

  # ユーザーがいいねした投稿の一覧表示
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites_index'

  # ユーザープロフィール関連のルーティング
  resources :users, only: %i[show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # DM機能のルーティング
  resources :chats, only: %i[index show create destroy]

  # 通知一覧画面へのルーティング
  resources :notifications, only: %i[index]
end

app/models/notification.rb
class Notification < ApplicationRecord
  #新着通知からデータを取得
  default_scope -> { order(created_at: :desc) }

  # アソシエーション
  belongs_to :mystery, optional: true
  belongs_to :comment, optional: true
  belongs_to :chat, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.all.page(params[:page]).per(10)
    # 通知一覧を開いたらcheckedをtrueに更新して確認済みにする
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<h3 class="header mb-3">通知一覧</h3>
<div class="col-10 offset-1 notification-box py-2">
  <ul class="notification-list mb-0">
    <% @notifications.each do |notification| %>
      <% case notification.action %>
      <% when "favorite" %>
        <li>
          <i class="fas fa-heart"></i>
          <%= link_to user_path(notification.visitor) do %>
            <%= attachment_image_tag notification.visitor, :profile_image, size:"40x40", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded-circle mx-2" %>
            <%= notification.visitor.name %>
          <% end %>
          さんがあなたの謎解き（
          <%= link_to notification.mystery.title, mystery_path(notification.mystery_id) %>
          ）にいいねしました！
        </li>
      <% when "comment" %>
        <li>
          <i class="fas fa-comments"></i>
          <%= link_to user_path(notification.visitor) do %>
            <%= attachment_image_tag notification.visitor, :profile_image, size:"40x40", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded-circle mx-2" %>
            <%= notification.visitor.name %>
          <% end %>
          さんがあなたの謎解き（
          <%= link_to notification.mystery.title, mystery_path(notification.mystery_id) %>
          ）にコメントしました！
        </li>
      <% when "follow" %>
        <li>
          <i class="fas fa-user-plus"></i>
          <%= link_to user_path(notification.visitor) do %>
            <%= attachment_image_tag notification.visitor, :profile_image, size:"40x40", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded-circle mx-2" %>
            <%= notification.visitor.name %>
          <% end %>
          さんにフォローされました！
        </li>
      <% when "chat" %>
        <li>
          <i class="fas fa-envelope"></i>
          <%= link_to user_path(notification.visitor) do %>
            <%= attachment_image_tag notification.visitor, :profile_image, size:"40x40", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded-circle mx-2" %>
            <%= notification.visitor.name %>
          <% end %>
          さんから
          <%= link_to "メッセージ", chat_path(notification.visitor) %>
          が届きました！
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<%= paginate @notifications %>