config/routes.rb
Rails.application.routes.draw do
  # devise関連のルーティング
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  # 検索機能のルーティング
  get 'search' => 'searches#search', as: 'search'

  # 謎解き投稿関連のルーティング
  get 'sort' => 'mysteries#sort', as: 'sort'
  resources :mysteries do
    # コメント機能
    resources :comments, only: %i[create update destroy]
    # いいね機能
    resource :favorites, only: %i[create destroy]
  end

  # 退会機能のルーティング
  # 退会確認画面の表示
  get 'users/unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  # ユーザーの有効ステータスを更新
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'users/withdraw' => 'users#withdraw'

  # ユーザーがいいねした投稿の一覧表示
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites_index'

  # ユーザープロフィール関連のルーティング
  resources :users, only: %i[show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # DM機能のルーティング
  resources :chats, only: %i[index show create destroy]

  # 通知一覧画面へのルーティング
  resources :notifications, only: %i[index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :mysteries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # 自分から送った通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手から受け取る通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # バリデーション
  validates :name, :tellphone_number, :email, :birthday, presence: true
  validates :name, length: { in: 1..10 }
  validates :introduction, length: { maximum: 200 }
  validates :tellphone_number, numericality: :only_integer

  # 画像アップ用のメソッド
  attachment :profile_image

  # フォロー機能用
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォロー解除用
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # 引数で渡したユーザーをフォローしているか
  def following?(user)
    followings.include?(user)
  end

  # フォローの通知
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, self.id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: self.id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 検索フォームに入力された文字列をnameに含むユーザーを探す
  def self.search_for(keyword)
    User.where('name LIKE ?', "%#{keyword}%")
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_inactive_user, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected

  # 退会済ユーザーのログインを拒否する
  def reject_inactive_user
    @user = User.find_by(email: params[:user][:email])
    return unless @user

    if @user.valid_password?(params[:user][:password]) && !@user.is_actived
      redirect_to new_user_session_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @notifications = current_user.passive_notifications.where(checked: false)
      @chat_notifications = @notifications.where(action: 'chat')
      @mysteries = current_user.mysteries.page(params[:page]).reverse_order
    else
      @mysteries = Mystery.opened.where(user_id: @user.id).page(params[:page]).reverse_order
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def favorites
    @user = User.find(params[:id])
    favorites_id = @user.favorites.pluck(:mystery_id)
    @mysteries = Mystery.opened.where(id: favorites_id).page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "プロフィールを更新しました！"
    else
      render 'edit'
    end
  end

  # 退会画面を表示する
  def unsubscribe
    @user = current_user
  end

  # ユーザーの有効ステータスをfalseに更新(論理削除)
  def withdraw
    @user = current_user
    @user.update(is_actived: false)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :birthday, :is_birthday_opened)
  end

  # 自分以外のユーザーのプロフィール編集画面にアクセスできないようにする
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
      flash[:notice] = "アクセスできません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="row">
  <% users.each do |user| %>
    <div class="col-3 px-3">
      <div class="card mb-3">
        <%= link_to user_path(user.id) do %>
          <%= attachment_image_tag(user, :profile_image, :fill, 200, 200, alt:"Profileimage", size:"200x200", fallback: "profile_image.jpg", class:"card-img-top") %>
        <% end %>
        <div class="card-body text-center">
          <% if user.is_actived %>
            <h5 class="card-title">
              <%= link_to user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </h5>
          <% else %>
            <h5 class="card-title disabled">
              <%= user.name %>(退会済み)
            </h5>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate users %>

app/views/users/_profile.html.erb
<div class="card offset-1 col-10 mb-3">
  <div class="row no-gutters">
    <div class="col-3 my-auto">
      <%= attachment_image_tag user, :profile_image, size:"180x180", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded" %>
    </div>
    <div class="col-9">
      <div class="card-body">
        <h5 class="card-title"><%= user.name %></h5>
        <% if user.is_birthday_opened %>
          <span>誕生日：<%= l user.birthday, format: :birthday  %></span>
        <% else %>
          <span>誕生日：非公開</span>
        <% end %>
        <% if user.introduction %>
          <p class="card-text mt-3">
            <%= safe_join(user.introduction.split("\n"),tag(:br)) %>
          </p>
        <% end %>
      </div>
      <div>
        <ul class="nav profile-list">
          <li class="nav-item">
            <%= link_to "投稿", user_path(user), remote: true, class:"nav-link active" %>
          </li>
          <li class="nav-item" id="follow-count">
            <%= link_to user_followings_path(user), remote: true, class:"nav-link" do %>
              フォロー
              <%= user.followings.count %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_followers_path(user), remote: true, class:"nav-link follower-link" do %>
              フォロワー
              <%= user.followers.count %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to favorites_index_path(user), remote: true, class:"nav-link" do %>
              いいね <i class="fas fa-heart"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h3 class="header mb-4">プロフィール編集</h3>
<div class="col-8 offset-2">
  <%= render 'layouts/errors', model: @user %>
  <div class="form-box pb-3 pt-4">
    <%= form_with model:@user, local:true, method: :patch do |f| %>
      <div class="pl-3">
        <div class="form-group row">
          <%= f.label :name, "ニックネーム", class:"col-4" %>
          <%= f.text_field :name, class:"form-control col-7" %>
        </div>
        <div class="form-group row mt-4">
          <%= f.label :introduction, "プロフィール", class:"col-4" %>
          <%= f.text_area :introduction, rows:'5', class:"form-control col-7" %>
        </div>
        <div class="form-group row mt-4">
          <%= f.label :profile_image, "プロフィール画像", class:"col-4" %>
          <%= f.attachment_field :profile_image, class:"form-control-file col-7 pl-0" %>
        </div>
        <div class="form-group row mt-4">
          <%= f.label :birthday, "誕生日", class:"col-4" %>
          <%= f.date_select :birthday, {start_year: 1920, end_year: 2021} %>
        </div>
        <div class="form-group row mt-4 mb-5">
          <%= f.label :is_birthday_opened, "誕生日の公開設定", class:"col-4" %>
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_birthday_opened, true, class:"form-check-input" %>
            <label class="form-check-label">公開</label>
            <%= f.radio_button :is_birthday_opened, false, class:"form-check-input ml-2" %>
            <label class="form-check-label">非公開</label>
          </div>
        </div>
      </div>
      <div class="action text-center">
        <%= f.submit "更新", class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/favorites.js.erb
$(".content-box").html("<%= j(render 'mysteries/index_page', mysteries: @mysteries) %>");
$(".content-header").html("いいねした投稿一覧");

app/views/users/show.html.erb
<% if @user == current_user %>
  <div class="row mb-3">
    <div class="col-1 offset-4 my-auto px-0 text-right">
      <%= link_to chats_path, class:"mr-2" do %>
        <%= @chat_notifications.count %>
        <i class="fas fa-envelope"></i>
      <% end %>
      <%= link_to notifications_path do %>
        <%= @notifications.count %>
        <i class="fas fa-bell"></i>
      <% end %>
    </div>
    <h3 class="header col-2">マイページ</h3>
    <a class="mr-3 my-auto" data-toggle="collapse" href="#confcollapse" role="button" aria-expanded="false" aria-controls="confcollapse">
      <i class="fas fa-cogs"></i>
    </a>
    <div class="overflow-hidden my-auto">
      <div class="collapse" id="confcollapse">
        <%= link_to "プロフィール編集", edit_user_path(@user), class:"mr-2" %>
        <%= link_to "退会", confirm_unsubscribe_path %>
      </div>
    </div>
  </div>
<% else %>
  <h3 class="header"><%= @user.name %> さんのプロフィール</h3>
  <% if @user.is_actived %>
    <div class="row mt-1 mb-3">
      <div class="offset-4 col-4 text-center">
        <span class="follow-btn">
          <%= render 'relationships/follow_btn', user: @user %>
        </span>
        <span class="chat-link">
          <%= render 'chats/chat_link', user: @user %>
        </span>
      </div>
    </div>
  <% else %>
    <p class="text-center">削除済みユーザー</p>
  <% end %>
<% end %>

<%= render 'users/profile', user: @user %>
<h4 class="content-header mb-3">投稿一覧</h4>
<div class="content-box">
  <%= render 'mysteries/index_page', mysteries: @mysteries %>
</div>

app/views/users/show.js.erb
$(".content-box").html("<%= j(render 'mysteries/index_page', mysteries: @mysteries) %>");
$(".content-header").html("投稿一覧");

app/views/users/unsubscribe.html.erb
<h3 class="header mb-5">退会確認</h3>

<div class="unsubscribe-message-box offset-2 col-8 text-center py-5">
  <h5><%= @user.name %> さん、本当に退会しますか？</h5>
    <p>退会すると、これまでに作成した謎解きやフォローしたユーザーとのDMなど、</br>
    このアカウントに関連する情報が利用できなくなります。</br>
    退会する場合は、『退会』をクリックしてください。</p>
  <div>
    <%= link_to '戻る', user_path(@user), class:"btn btn-primary mr-4" %>
    <%= link_to "退会", withdraw_user_path(@user), method: :patch, class:"btn btn-danger" %>
  </div>
</div>