config/routes.rb
Rails.application.routes.draw do
  # devise関連のルーティング
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  # 検索機能のルーティング
  get 'search' => 'searches#search', as: 'search'

  # 謎解き投稿関連のルーティング
  get 'sort' => 'mysteries#sort', as: 'sort'
  resources :mysteries do
    # コメント機能
    resources :comments, only: %i[create update destroy]
    # いいね機能
    resource :favorites, only: %i[create destroy]
  end

  # 退会機能のルーティング
  # 退会確認画面の表示
  get 'users/unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  # ユーザーの有効ステータスを更新
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'users/withdraw' => 'users#withdraw'

  # ユーザーがいいねした投稿の一覧表示
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites_index'

  # ユーザープロフィール関連のルーティング
  resources :users, only: %i[show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # DM機能のルーティング
  resources :chats, only: %i[index show create destroy]

  # 通知一覧画面へのルーティング
  resources :notifications, only: %i[index]
end

app/models/mystery.rb
class Mystery < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # バリデーション
  validates :title, :discription, :answer, :answer_discription, :difficulty_level, presence: true

  # 画像アップ用のメソッド
  attachment :image
  attachment :answer_image

  # 引数で渡しているuserがいいねしている投稿か
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 非公開設定の投稿を除く
  def self.opened
    Mystery.where(is_opened: true)
  end

  # いいねが多い投稿トップ３を取得
  def self.favorite_ranking
    Mystery.opened.left_joins(:favorites).group(:id).order(Arel.sql('COUNT(favorites.id) desc')).limit(3).pluck(:id)
  end

  # 検索フォームに入力された文字列をtitleかdiscriptionに含む投稿を探す
  def self.search_for(keyword)
    Mystery.where('title LIKE ?', "%#{keyword}%").or(Mystery.where('discription LIKE ?', "%#{keyword}%"))
  end

  # 選択された方法で投稿を並べ替える
  def self.sort(method)
    case method
    when 'new'
      return all.order(created_at: :DESC)
    when 'old'
      return all.order(created_at: :ASC)
    when 'favorites'
      return left_joins(:favorites).group(:id).order(Arel.sql('COUNT(favorites.id) desc'))
    when 'difficulty'
      return all.order(difficulty_level: :DESC)
    end
  end

  # 新着いいねの通知
  def create_notification_favorite(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and mystery_id = ? and action = ? ", current_user.id, self.user_id, self.id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        mystery_id: self.id,
        visited_id: self.user_id,
        action: 'favorite'
      )
      notification.save if notification.valid?
    end
  end

  # 新着コメントの通知
  def create_notification_comment(current_user, comment_id)
    notification = current_user.active_notifications.new(
      mystery_id: self.id,
      comment_id: comment_id,
      visited_id: self.user_id,
      action: 'comment'
    )
    notification.save if notification.valid?
  end

end

app/controllers/mysteries_controller.rb
class MysteriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mystery, only: %i[show edit update destroy]
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def index
    @mysteries = Mystery.opened.page(params[:page]).reverse_order
  end

  def sort
    method = params[:method]
    @mysteries = Mystery.sort(method).opened.page(params[:page])
    render 'index'
  end

  def show
    if !@mystery.is_opened && @mystery.user != current_user
      redirect_to mysteries_path, notice: "非公開投稿のため、アクセスできません。"
    end
    @comment = Comment.new
  end

  def new
    @mystery = Mystery.new
  end

  def create
    @mystery = Mystery.new(mystery_params)
    @mystery.user_id = current_user.id

    if @mystery.save
      redirect_to mystery_path(@mystery.id)
      flash[:notice] = "新しい謎解きを投稿しました！"
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @mystery.update(mystery_params)
      redirect_to mystery_path(@mystery)
      flash[:notice] = "更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    if @mystery.destroy
      redirect_to mysteries_path
      flash[:notice] = "投稿を削除しました。"
    else
      @comment = Comment.new
      render 'show'
    end
  end

  private

  def mystery_params
    params.require(:mystery).permit(:title, :discription, :image, :answer, :answer_image, :answer_discription, :difficulty_level, :is_opened)
  end

  def set_mystery
    @mystery = Mystery.find(params[:id])
  end

  # 自分以外のユーザーの投稿は編集削除できないようにする
  def ensure_correct_user
    @user = @mystery.user
    unless @user == current_user
      redirect_to mystery_path(@mystery)
      flash[:notice] = "アクセスできません。"
    end
  end
end

app/helpers/mysteries_helper.rb
module MysteriesHelper
end

app/views/mysteries/_form.html.erb
<div class="form-box pb-3 pt-4">
<%= form_with model: mystery, local:true do |f| %>
  <div class="form-group row">
    <%= f.label :title, "タイトル", class:"col-4" %>
    <%= f.text_field :title, autofocus: true, class:"form-control col-7" %>
  </div>

  <div class="form-group row">
    <%= f.label :image, "画像", class:"col-4" %>
    <%= f.attachment_field :image, class:"form-control-file col-7" %>
  </div>
  <div class="form-group row">
    <%= f.label :discription, "問題文", class:"col-4" %>
    <%= f.text_area :discription, rows:'5', class:"form-control col-7" %>
  </div>
  <div class="form-group row">
    <%= f.label :answer, "答え", class:"col-4" %>
    <%= f.text_field :answer, class:"form-control col-7" %>
  </div>
  <div class="form-group row">
    <%= f.label :answer_discription, "解説", class:"col-4" %>
    <%= f.text_area :answer_discription, rows:'5', class:"form-control col-7" %>
  </div>
  <div class="form-group row">
    <%= f.label :answer_image, "解説用画像", class:"col-4" %>
    <%= f.attachment_field :answer_image, class:"form-control-file col-7" %>
  </div>
  <div class="form-group row" id="difficulty_level">
    <label class="col-4">難易度</label>
  </div>
  <div class="form-group row">
    <%= f.label :is_opened, "公開設定", class:"col-4" %>
    <div class="radio-button-box">
      <%= f.radio_button :is_opened, true %>
      <%= f.label :is_opened, "公開", {value: true, style: "display: inline-block;"} %>
      <%= f.radio_button :is_opened, false, class:"ml-3" %>
      <%= f.label :is_opened, "非公開", {value: false, style: "display: inline-block;"} %>
    </div>
  </div>

  <div class="action">
    <%= f.submit btn_string, class:"btn btn-primary col-2 offset-5 mt-4" %>
  </div>
<% end %>
</div>

<script>
  $('#difficulty_level').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    half: true,
    scoreName: 'mystery[difficulty_level]'
  });
</script>

app/views/mysteries/_index.html.erb
<div class="row text-center">
  <% mysteries.each do |mystery| %>
    <div class="col-3">
      <div class="card mb-3">
        <%= attachment_image_tag(mystery, :image, :fill, 250, 180, alt:"Mysteryimage", fallback: "no_image.jpg", size:"250x180", class:"card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">
            <% if mystery.is_opened %>
              <%= link_to mystery_path(mystery.id) do %>
                <%= mystery.title %>
              <% end %>
            <% else %>
              <%= link_to mystery_path(mystery.id) do %>
                <%= mystery.title %> <i class="fas fa-lock"></i>
              <% end %>
            <% end %>
          </h5>
          <p class="card-text" id="difficulty_level_<%= mystery.id %>"></p>
          <!--難易度の星の表示-->
          <script>
          $('#difficulty_level_<%= mystery.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= mystery.difficulty_level %>,
          });
          </script>
          <span class="favorite-count"><i class="fas fa-heart"></i> <%= mystery.favorites.count %></span>
          <span class="ml-2 comment-count"><i class="fas fa-comments"></i> <%= mystery.comments.count %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/mysteries/_index_page.html.erb
<div class="row text-center">
  <% mysteries.each do |mystery| %>
    <div class="col-3">
      <div class="card mb-3">
        <%= attachment_image_tag(mystery, :image, :fill, 250, 180, alt:"Mysteryimage", fallback: "no_image.jpg", size:"250x180", class:"card-img-top") %>
        <div class="card-body">
          <h5 class="card-title">
            <% if mystery.is_opened %>
              <%= link_to mystery_path(mystery.id) do %>
                <%= mystery.title %>
              <% end %>
            <% else %>
              <%= link_to mystery_path(mystery.id) do %>
                <%= mystery.title %> <i class="fas fa-lock"></i>
              <% end %>
            <% end %>
          </h5>
          <p class="card-text" id="difficulty_level_<%= mystery.id %>"></p>
          <!--難易度の星の表示-->
          <script>
          $('#difficulty_level_<%= mystery.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= mystery.difficulty_level %>,
          });
          </script>
          <span class="favorite-count"><i class="fas fa-heart"></i> <%= mystery.favorites.count %></span>
          <span class="ml-2 comment-count"><i class="fas fa-comments"></i> <%= mystery.comments.count %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate mysteries, remote: true %>

app/views/mysteries/_ranking.html.erb
<div class="card px-0">
  <%= attachment_image_tag mystery, :image, alt:"Mysteryimage", size:"280x180", fallback: "no_image.jpg", class:"card-img-top" %>
  <div class="card-body">
    <h5 class="card-title">
      <%= link_to mystery_path(mystery.id) do %>
        <%= mystery.title %>
      <% end %>
    </h5>
    <p class="card-text" id="difficulty_level_<%= mystery.id %>"></p>
    <!--難易度の星の表示-->
    <script>
    $('#difficulty_level_<%= mystery.id %>').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      score: <%= mystery.difficulty_level %>,
    });
    </script>
    <span class="favorite-count"><i class="fas fa-heart"></i> <%= mystery.favorites.count %></span>
    <span class="ml-2 comment-count"><i class="fas fa-comments"></i> <%= mystery.comments.count %></span>
    <p class="mt-2 mb-0">by <%= mystery.user.name %>さん</p>
  </div>
</div>

app/views/mysteries/_sort_form.html.erb
<div class="col-3 offset-4 mx-auto my-3">
  <%= form_with model: mystery, url: sort_path, method: :get, local: true, class:"form-inline" do |f| %>
    <div class="form-group">
      <%= f.select :method, [['投稿が新しい順', 'new'],['投稿が古い順', 'old'],['いいねが多い順','favorites'],['難易度の高い順','difficulty']], class:"form-control" %>
    </div>
    <div class="action">
      <%= f.submit "並び替え", class:"ml-2 btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/mysteries/edit.html.erb
<h3 class="header mb-3">投稿編集</h3>
<div class="offset-2 col-8">
  <%= render 'layouts/errors', model: @mystery %>
  <%= render 'form', mystery: @mystery, btn_string: "更新！" %>
</div>

app/views/mysteries/index.html.erb
<h3 class="header">謎解き一覧</h3>
<%= render 'sort_form', mystery: @mystery %>

<%= render 'index', mysteries: @mysteries %>
<%= paginate @mysteries %>

app/views/mysteries/new.html.erb
<h3 class="header mb-3">謎解き投稿</h3>
<div class="offset-2 col-8">
  <%= render 'layouts/errors', model: @mystery %>
  <%= render 'form', mystery: @mystery, btn_string: "作成" %>
</div>

app/views/mysteries/show.html.erb
<h3 class="header"><%= @mystery.title %></h3>
<!--ログインユーザーの投稿なら編集ボタンと削除ボタンを表示する-->
<% if @mystery.user == current_user %>
  <div class="text-center mb-2">
    <%= link_to edit_mystery_path(@mystery) do %>
      <i class="fas fa-edit mr-1"></i>
    <% end %>
    <%= link_to mystery_path(@mystery), method: :delete, data: {confirm: "編集ページから非公開に変更もできますが、削除してよろしいですか？"} do %>
      <i class="fas fa-trash-alt ml-1"></i>
    <% end %>
  </div>
<% end %>

<div class="card" id="<%= @mystery.id %>-card">
  <!--カードのヘッダー部-->
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs" id="mysteryTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="main-tab" data-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">謎解き</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="answer-tab" data-toggle="tab" href="#answer" role="tab" aria-controls="answer" aria-selected="false">解説</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="user-tab" data-toggle="tab" href="#user" role="tab" aria-controls="user" aria-selected="false">投稿者</a>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="mysteryTabContent">

    <!--謎解き問題タブ-->
    <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="main-tab">
      <div class="row">
        <div class="col-4 ml-3 my-auto">
          <%= link_to Refile.attachment_url(@mystery, :image), "data-lightbox":"mystery_img", "data-title":"問題画像" do %>
            <%= attachment_image_tag @mystery, :image, size:"300x200", alt:"MysteryImage", fallback:"no_image.jpg" %>
          <% end %>
        </div>
        <div class="col-7 card-body">
          <div class="row">
            <h5 class="card-title"><%= @mystery.title %></h5>
            <span class="ml-5" id="favorite-btn">
              <%= render 'favorites/favorite-btn', mystery: @mystery %>
            </span>
            <span class="ml-2 comment-count"><i class="fas fa-comments"></i> <%= @mystery.comments.count %></span>
          </div>
          <h6 class="card-subtitle">難易度：<span class="difficulty_level"></span></h6>
          <!--難易度の星の表示-->
          <script>
          $('.difficulty_level').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @mystery.difficulty_level %>,
          });
          </script>
          <p class="card-text mt-3"><%= safe_join(@mystery.discription.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>

    <!--謎解き解説タブ-->
    <div class="tab-pane fade" id="answer" role="tabpanel" aria-labelledby="answer-tab">
      <div class="row">
        <div class="col-4 ml-3 my-auto">
          <%= link_to Refile.attachment_url(@mystery, :answer_image), "data-lightbox":"answer_img", "data-title":"解説画像" do %>
            <%= attachment_image_tag @mystery, :answer_image, alt:"No Image", size:"300x200", fallback:"no_image.jpg" %>
          <% end %>
        </div>
        <div class="col-7 card-body">
          <h5 class="card-title"><%= @mystery.answer %></h5>
          <p class="card-text">
            解説：</br>
            <%= safe_join(@mystery.answer_discription.split("\n"),tag(:br)) %>
          </p>
        </div>
      </div>
    </div>

    <!--投稿者タブ-->
    <div class="tab-pane fade" id="user" role="tabpanel" aria-labelledby="user-tab">
      <div class="row">
        <div class="col-3 ml-5 my-2">
          <%= attachment_image_tag @mystery.user, :profile_image, size:"180x180", alt:"ProfileImage", fallback:"profile_image.jpg", class:"rounded-circle"; %>
        </div>
        <div class="col-8 ml-2 card-body">
          <h5 class="card-title">
            <%= link_to user_path(@mystery.user) do %>
              <%= @mystery.user.name %>
            <% end %>
          </h5>
          <p>フォロー： <%= @mystery.user.followings.count %></p>
          <p class="follow-count">フォロワー： <%= @mystery.user.followers.count %></p>
          <% if @mystery.user.is_actived %>
            <span class="follow-btn">
              <%= render 'relationships/follow_btn', user: @mystery.user %>
            </span>
          <% else %>
            <p>削除済みユーザー</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-5 comment-box">
  <!--コメント投稿フォーム-->
  <div class="col-4">
    <div class="error-messages">
      <%= render 'layouts/errors', model: @comment %>
    </div>
    <%= render 'comments/form', mystery: @mystery, comment: @comment %>
  </div>
  <!--コメント一覧-->
  <div class="col-7 offset-1">
    <h5 class="mb-0 pb-2"><%= @mystery.comments.count %> 件のコメント：</h5>
    <div class="comment-index">
      <%= render 'comments/index', mystery: @mystery %>
    </div>
  </div>
</div>