config/routes.rb
Rails.application.routes.draw do
  # devise関連のルーティング
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  # 検索機能のルーティング
  get 'search' => 'searches#search', as: 'search'

  # 謎解き投稿関連のルーティング
  get 'sort' => 'mysteries#sort', as: 'sort'
  resources :mysteries do
    # コメント機能
    resources :comments, only: %i[create update destroy]
    # いいね機能
    resource :favorites, only: %i[create destroy]
  end

  # 退会機能のルーティング
  # 退会確認画面の表示
  get 'users/unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  # ユーザーの有効ステータスを更新
  patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
  put 'users/withdraw' => 'users#withdraw'

  # ユーザーがいいねした投稿の一覧表示
  get 'users/:id/favorites' => 'users#favorites', as: 'favorites_index'

  # ユーザープロフィール関連のルーティング
  resources :users, only: %i[show edit update] do
    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # DM機能のルーティング
  resources :chats, only: %i[index show create destroy]

  # 通知一覧画面へのルーティング
  resources :notifications, only: %i[index]
end

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div id="error-message-box" class="offset-3 col-6 mb-3">
    <h5><%= model.errors.count %> 件のエラーが発生しました</h5>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="error-message-box mb-3">
    <h5><%= model.errors.count %> 件のエラーが発生しました</h5>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MysteryClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--画像拡大-->
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </head>

  <body>
    <header class="shadow-sm mb-3">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div>
          <%= link_to root_path, class:"navbar-brand" do %>
            <%= image_tag 'mysteryclub_logo.png', size: "180x80" %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarContent">
          <div>
            <ul class="navbar-nav ml-3">
              <% if user_signed_in? %>
                <li class="nav-item mr-3">
                  <%= link_to "マイページ", user_path(current_user), class:"nav-link text-right" %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to "謎解き一覧", mysteries_path, class:"nav-link text-right" %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to "新規作成", new_mystery_path, class:"nav-link text-right" %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-right" %>
                </li>
              <% else %>
                <li class="nav-item mr-3">
                  <%= link_to "About", about_path, class:"nav-link text-right" %>
                </li>
                <li class="nav-item mr-3">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-right" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link text-right" %>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="ml-auto">
            <%= form_with url: search_url, method: :get, local: true, class:"d-flex" do |f| %>
              <%= f.search_field :keyword, class: "form-control me-2", placeholder: "Search" %>
              <%= f.hidden_field :model, value: "Mystery" %>
              <%= button_tag type:"submit", class:"btn btn-dark" do %>
                <i class="fa fa-search"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <p class="notice text-center"><b><%= notice %></b></p>
      <%= yield %>
      </div>
    </main>
    <footer class="mt-5">
      <p class="text-white"> © MysteryClub by Yu Matsui</p>
    </footer>
  </body>
</html>